### ISSUE TITLE
"Self" package id not supported for packages.config style projects

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#13]
I created a legacy csharp project that has `packages.config` file for managing nuget packages.

After adding a nuget package that has a util pack task factory task in and building:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "self" package ID is not supported when the caller file of this task factory is not in local repositories: C:\Users\Darrell\.nuget\packages\.	ClassLibrary5		
```

I think this is because the nuget packages in this instance are located in a local packages directory..

**Comment by stazz** [comment]
Ah, most likely this is due to the fact that it is in NuGet (protocol) V2 package repository, instead of NuGet V3. The resolution logic in task factory always assumes V3, since I thought no one would be using that legacy stuff anymore, but now that I think about it, I guess some people can be 'forced' to using V2 by circumstances (legacy dependency or tools).

I'll modify the code so that it will support V2 repositories as well.
