### ISSUE TITLE
Caching of restores

### ISSUE THREAD

**Issue by jnevins-gcm** [stazz/UtilPack#28]
I'm using a package that uses UtilPack.NuGet (GitVersionTask). It's extremely slow because every project that uses GitVersionTask in turn has UtilPack.NuGet try to resolve all dependencies with NuGet every time. So for every single project being built in a solution, I see:

[NuGet Minimal]: Restoring packages for C:\Users\user\AppData\Local\Temp\yr2nqvrh.qcc\dummy...

is there a way to have UtilPack not try to do a restore every time?

**Comment by stazz** [comment]
Hi,

I've added caching of `BoundRestoreCommandUser` objects (which in turn cache restores themselves) in version `2.5.0` of [UtilPack.NuGet.MSBuild](https://www.nuget.org/packages/UtilPack.NuGet.MSBuild) package. Is the GitVersionTask using that version or newer?

Edit: I forgot to mention that the cache being used is in-process. So if you have one big build which utilizes the UtilPack.NuGet.MSBuild task factory, and it is used to restore the same package, that package restoration result will be cached on first usage within the same build and used on subsequent usages, as long as the process is the same. The feature to cache the restoration results so that they would be persistable across multiple build runs (basically, writing the lock file to disk) is not yet implemented.

**Comment by stazz** [comment]
If your issue was about persistent caching of restore results, it is now tracked in #29 .

**Comment by jnevins-gcm** [comment]
Updating to 2.5.0 manually within the projects that use GitVersionTask worked! Thanks!!

Should I upgrade it to 2.5.0 or 2.6.0? Also, is there any way to suppress this single warning without changing the logging level of our whole build?

`Task factory warning NMSBT010: There is a mismatch between SDK NuGet version (4.7.0) and the NuGet version the task factory was compiled against (4.6.0). There might occur some exotic errors.`

**Comment by stazz** [comment]
Glad to hear that caching in 2.5.0 worked for you! The different between 2.5.0 and 2.6.0 is that the latter is aware of NuGet 4.7.0, so you will get rid of that warning by upgrading to 2.6.0.

I am also preparing version 2.7.0, which can automatically deduce .NET Core 2.1 environment, but I am not sure yet when it'll be out.

**Comment by jnevins-gcm** [comment]
This is wonderful, thanks.

Though I'm still getting 
`
MSBUILD : Task factory warning NMSBT010: There is a mismatch between SDK NuGet version (4.7.0) and the NuGet version the task factory was compiled against (4.6.0). There might occur some exotic errors.`

with 2.6.0

Does GitVersionTask also need to update to 2.6.0 itself?

**Comment by stazz** [comment]
No, I don't think it does. I tried reproducing that by running a task but I didn't get the warning. Maybe try setting verbosity to detailed or even diagnostic to see which path MSBuild loads the task factory from, to reveal which version of UtilPack.NuGet.MSBuild is actually used?

**Comment by jnevins-gcm** [comment]
Wow! That's bizarre - I tried to remove 2.4.0 and 2.5.0 from my nuget cache which made me notice that dotnet cli was doing its process caching thing and that both 2.4.0, 2.5.0 and 2.6.0 files were all locked)...so I stopped all dotnet.exe processes and the warning went away after the next package restore. I guess you're doing AssemblyResolution at the dotnet.exe process itself, not within an isolated LoadContext?

**Comment by stazz** [comment]
All assembly resolution in both .NET Desktop and .NET Core is always done within the process itself, but by default, the UtilPack.NuGet.MSBuild locks the files themselves and not their copies (i.e. not doing the [shadow-copying](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/shadow-copy-assemblies)).

You can enable the shadow-copying of assembly files in UtilPack.NuGet.MSBuild by setting `CopyToFolderBeforeLoad` task factory parameter (see also [full list of parameters](/CometaSolutions/UtilPack/tree/develop/Source/UtilPack.NuGet.MSBuild)) to `true` or to some path which will hold the copied assemblies. That way, the original assemblies remain unlocked. :)

**Comment by dazinator** [comment]
@stazz @jnevins-gcm thanks both for this, I have updated GitVersion's `GitVersionTask` to use 2.6.0. Hopefully this will carry with it the speed improvements for restoration and resolve the build warning.

**Comment by dazinator** [comment]
This issue of build warning has resurfaced again with the release of nuget 4.8.0.

**Comment by stazz** [comment]
Geezus, the NuGet versions sure keep on coming! I will publish new version of UtilPack.NuGet which is 4.8.0-aware asap, probably this weekend!

P.S. Making UtilPack.NuGet as [.NET Core Global Tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) is something that might help with NuGet version problems (tracked in #31 now).

**Comment by stazz** [comment]
Release version `2.7.0` which contains support for NuGet 4.8.0.

Important! The desktop assemblies are not contained in `build/net46` folder instead of `build/net45` folder, as I finally moved the desktop to use newer version of NuGet as well. So if @dazinator you have any hard-coded paths to `net45`, you should change them to `net46` for this release. :)
