### ISSUE TITLE
UtilPack.NuGet.MsBuild and Mono

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#32]
Hello!
Seen an issue when running on mono, here are the details here:

https://gist.github.com/ermshiperete/18bd905ca9155f3052dca0864a85d0da

`dotnet build` works fine on the same environment.

Original issue logged: https://github.com/GitTools/GitVersion/issues/1460#issuecomment-419485453

I think this might be a problem with the task factory not supporting mono msbuild environments, im not sure if this relates to particular versions of mono or mono in general. The linked issue describes the op's environment including mono version.

**Comment by stazz** [comment]
Interesting, this is a hard crash (whole runtime just halts instead of e.g. an exception being thrown). This happens when the the assembly holding the task type has been located, but the actual task type needs to be loaded. I really didn't plan to be prepared for Mono when I was writing the UtilPack, as I thought it would become obsolete now that there exists .NET Core for Linux.

The task factory thinks it is in .NET Desktop environment, since `Detected current NuGet framework to be ".NETFramework,Version=v4.6.1"` is printed. I think this might not be supported on Mono running in Linux. I need to find out whether loading .NET Core version of the assembly would work in Mono on Linux.

**Comment by stazz** [comment]
This is now fixed as well as it can be - the dedicated AppDomains are no longer used if Mono framework is detected. While this fixes most issues, it might cause some issues when UtilPack.NuGet.MSBuild task factory is used to load different tasks within same process.
