### ISSUE TITLE
NuGet version increment strikes again!

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#34]
As per: https://github.com/stazz/UtilPack/issues/19
It looks like MsBuild have incremented their NuGet dependency and it has a breaking change this time:

> If I'm more specific then microsoft/dotnet:2.1.403-sdk works (with warning) but microsoft/dotnet:2.1.500-sdk fails with the error.

Error is:

> MSBUILD : Task factory warning NMSBT010: There is a mismatch between SDK NuGet version (4.9.0) and the NuGet version the task factory was compiled against (4.8.0). There might occur some exotic errors. [/app/example.serialisation/example.serialisation.fsproj] MSBUILD : Task factory error NMSBT001: Exception in initialization: System.MissingMethodException: Method not found: 'Void NuGet.Commands.RestoreRequest..ctor(NuGet.ProjectModel.PackageSpec, NuGet.Commands.RestoreCommandProviders, NuGet.Protocol.Core.Types.SourceCacheContext, NuGet.Common.ILogger)'. [/app/example.serialisation/example.serialisation.fsproj]

**Comment by dazinator** [comment]
I am wondering...

I am assuming this problem crops up because `UtilPack` needs to resolve whatever version of NuGet is currently loaded at runtime (by msbuild), and this version changes as people use later versions of msbuild with the netcore sdk, and thus its API changes. I haven't looked at the code, but I assume you use reflection to find the relevent nuget assembly and invoke the necessary types?

I am wondering, to solve this, could you perhaps load a fixed / specific version of nuget (perhaps bundled with utilpack) into a seperate assembly load context, and then invoke your nuget operations there? Instead of being dependent upon the hosts version, this would allow you to use your own compatible version which would remain fixed.

**Comment by LordMike** [comment]
Which functionality is explicitly required? I can find the place the warning is emitted, but I haven't had time to map out all the methods / properties / types that are found.

**Comment by stazz** [comment]
Hello!

Ah fun, the NuGet has *yet again* made binary-incompatible change in minor or build version increase. It looks like the signature for `RestoreRequest` type constructor has been changed. I will just need to bump the version once again.

@dazinator you are correct about the NuGet version detection in .NET Core: when the task factory facade type is loading, it "sniffs" which NuGet version is loaded currently by the MSBuild, and tries to use the actual task factory assembly compiled against that specific NuGet version. And when there isn't such assembly, it defaults to latest and emits that warning, and crosses fingers and hopes for the best :)

I don't have sources right now, but I remember reading about the mechanism, and basically when you invoke `dotnet build`, the NuGet assemblies (along with everything else in your `C:\Program Files\dotnet\sdk\<version>` directory on Windows) is marked as "trusted framework assembly", meaning that the custom AssemblyLoadContext callbacks are not even invoked for such assemblies. So AFAIK, at least some months ago, there was absolutely no way for `UtilPack` task factory to load exactly specific NuGet version within its assembly load context.

@LordMike The code is quite convoluted actually - this is because of nuances of assembly loading, task factories in MSBuild, and versioning problem altogether. The situation is especially bad on .NET Desktop side with its clumsy `AppDomain`s. This is just so that you will know this, in case you are wondering wtf is going on in a codebase when you look at it. :)

The current tip of `develop` branch is actually in a middle of handling #33 , so I won't be able to fix this right away from there, as all the project names etc have changed drastically. What I can do is check out the previous release of `UtilPack` task factory and compile it against NuGet `4.9.0`, and then push that version to NuGet public repo.

P.S. The current tip of `develop` branch contains the `NuGetUtils.Tool.Exec` .NET Core Global Tool package, which is also [published on NuGet public repo](https://www.nuget.org/packages/NuGetUtils.Tool.Exec/), which executes a method within assembly of a specified NuGet package - essentially the same functionality as with current `UtilPack`, minus the MSBuild-specific stuff. The downside is that it is properly useable only in .NET Core environment, but since it is used outside `dotnet build` context, the NuGet-versioning problem is not present in there. You guys might want to investigate that one.

**Comment by stazz** [comment]
> What I can do is check out the previous release of UtilPack task factory and compile it against NuGet 4.9.0, and then push that version to NuGet public repo.

Except that I can't - it seems that [the latest published version](https://www.nuget.org/packages/NuGet.Commands) on public NuGet repository is still `4.8.0`. It seems that you are using .NET Core via DockerHub, so they have published the newest SDK and associated NuGet packages there, but not to nuget.org . -_-

I need to investigate this more since it seems like it's more complicated than just bumping version (at least until MS releases new version of `NuGet.Commands` package.

**Comment by LordMike** [comment]
"woops"
\- Nuget team

**Comment by LordMike** [comment]
@stazz `4.9.0` is out in an rtm version, https://www.nuget.org/packages/NuGet.Commands/4.9.0-rtm.5658

**Comment by stazz** [comment]
So it seems! I'll get on it to make a 4.9.0-compatible release.

Btw, it seems that 4.8.1 never got to nuget.org ... I hope that won't cause trouble.

**Comment by stazz** [comment]
@dazinator @LordMike The 4.9.0-compatible version of UtilPack is [now uploaded to nuget.org](https://www.nuget.org/packages/UtilPack.NuGet.MSBuild/2.9.0). It's built against the latest `4.9.0-rtm.5658` version of NuGet.Commands package, and indeed there was one place where the constructor had new argument. That's fixed now.

**Comment by LordMike** [comment]
@stazz will you handle both the 4.8.x and the 4.9.x versions - by switching at runtime?

**Comment by stazz** [comment]
@LordMike Yes, the `2.9.0` version of UtilPack will handle both 4.8.x and 4.9.x versions of NuGet (in fact, if you check package contents, the backwards compatibility goes all the way to 4.3.x). 👍

**Comment by dazinator** [comment]
Closing

**Comment by czeslav87** [comment]
related  - https://github.com/GitTools/GitVersion/issues/1554
