### ISSUE TITLE
Can you add topics in this repository?

### ISSUE THREAD

**Issue by Neustradamus** [stazz/UtilPack#36]
Dear @stazz,

In first, I wish you a Happy New Year!

Can you add in this repository, topics?
- scram
- scram-sha-1
- scram-sha-256
- scram-sha-512

Thanks in advance.

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by stazz** [comment]
Hello @Neustradamus !

Thank you, and I wish you a Happy New Year as well! 😄  Thank you also for opening the issue and providing clear description.

I am not actively maintaining this repo and included libraries anymore due to lack of free time. But I will try to figure out something for this and the other issue you created on this weekend. 👍

**Comment by stazz** [comment]
Topics added! 👍

**Comment by Neustradamus** [comment]
@stazz: Thanks!
